CREATE TABLE Equipo (
    codigo_equipo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    estadio VARCHAR2(100) NOT NULL,
    aforo NUMBER NOT NULL,
    fundacion NUMBER(4) NOT NULL,
    departamento VARCHAR2(50) NOT NULL
);

CREATE TABLE Presidente (
    dpi VARCHAR2(15) PRIMARY KEY,
    nombre1 VARCHAR2(50) NOT NULL,
    nombre2 VARCHAR2(50),
    nombre3 VARCHAR2(50),
    apellido1 VARCHAR2(50) NOT NULL,
    apellido2 VARCHAR2(50),
    fecha_nacimiento DATE NOT NULL,
    municipio VARCHAR2(50) NOT NULL,
    anio_elegido NUMBER(4) NOT NULL,
    codigo_equipo NUMBER UNIQUE,
    CONSTRAINT fk_presidente_equipo FOREIGN KEY (codigo_equipo)
        REFERENCES Equipo(codigo_equipo)
);

CREATE TABLE CorreoPresidente (
    id_correo_presidente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dpi VARCHAR2(15) NOT NULL,
    correo VARCHAR2(100) NOT NULL,
    CONSTRAINT fk_correo_presidente FOREIGN KEY (dpi)
        REFERENCES Presidente(dpi)
);

CREATE TABLE Jugador (
    codigo_jugador NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre1 VARCHAR2(50) NOT NULL,
    nombre2 VARCHAR2(50),
    apellido1 VARCHAR2(50) NOT NULL,
    apellido2 VARCHAR2(50),
    municipio VARCHAR2(50) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    posicion VARCHAR2(20) CHECK (posicion IN ('Portero','Defensa','Delantero','Centrocampista')),
    codigo_equipo NUMBER NOT NULL,
    CONSTRAINT fk_jugador_equipo FOREIGN KEY (codigo_equipo)
        REFERENCES Equipo(codigo_equipo)
);

CREATE TABLE CorreoJugador (
    id_correo_jugador NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_jugador NUMBER NOT NULL,
    correo VARCHAR2(100) NOT NULL,
    CONSTRAINT fk_correo_jugador FOREIGN KEY (codigo_jugador)
        REFERENCES Jugador(codigo_jugador)
);

CREATE TABLE Partido (
    codigo_partido NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    goles_casa NUMBER DEFAULT 0,
    goles_fuera NUMBER DEFAULT 0,
    codigo_equipo_casa NUMBER NOT NULL,
    codigo_equipo_fuera NUMBER NOT NULL,
    CONSTRAINT fk_partido_equipo_casa FOREIGN KEY (codigo_equipo_casa)
        REFERENCES Equipo(codigo_equipo),
    CONSTRAINT fk_partido_equipo_fuera FOREIGN KEY (codigo_equipo_fuera)
        REFERENCES Equipo(codigo_equipo)
);

-- Insertar equipos
INSERT INTO Equipo (nombre, estadio, aforo, fundacion, departamento) 
VALUES ('Real Mixco', 'Estadio Santo Domingo', 15000, 1970, 'Guatemala');

INSERT INTO Equipo (nombre, estadio, aforo, fundacion, departamento) 
VALUES ('Xelajú MC', 'Mario Camposeco', 11000, 1942, 'Quetzaltenango');

INSERT INTO Equipo (nombre, estadio, aforo, fundacion, departamento) 
VALUES ('Cobán Imperial', 'Verapaz', 12000, 1936, 'Alta Verapaz');


-- Insertar presidentes
INSERT INTO Presidente (dpi, nombre1, nombre2, nombre3, apellido1, apellido2, fecha_nacimiento, municipio, anio_elegido, codigo_equipo) 
VALUES ('1234567890101', 'Carlos', 'Enrique', NULL, 'Ramírez', 'López', DATE '1975-06-15', 'Mixco', 2020, 1);

INSERT INTO Presidente (dpi, nombre1, nombre2, nombre3, apellido1, apellido2, fecha_nacimiento, municipio, anio_elegido, codigo_equipo) 
VALUES ('9876543210101', 'Luis', 'Fernando', NULL, 'Gómez', 'Martínez', DATE '1980-03-22', 'Cobán', 2021, 3);


-- Insertar correos de presidentes
INSERT INTO CorreoPresidente (dpi, correo) VALUES
('1234567890101', 'carlos.ramirez@realmixco.gt');

INSERT INTO CorreoPresidente (dpi, correo) VALUES
('1234567890101', 'presidente.mixco@liga.gt');

INSERT INTO CorreoPresidente (dpi, correo) VALUES
('9876543210101', 'luis.gomez@coban.gt');


-- Insertar jugadores
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, municipio, fecha_nacimiento, posicion, codigo_equipo) 
VALUES ('José', 'Manuel', 'Pérez', 'García', 'Mixco', DATE '1995-04-10', 'Delantero', 1);

INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, municipio, fecha_nacimiento, posicion, codigo_equipo) 
VALUES ('Mario', NULL, 'López', 'Hernández', 'Mixco', DATE '1998-07-22', 'Defensa', 1);

INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, municipio, fecha_nacimiento, posicion, codigo_equipo) 
VALUES ('Carlos', 'Andrés', 'Ruiz', 'Mendoza', 'Xela', DATE '1992-01-15', 'Portero', 2);

INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, municipio, fecha_nacimiento, posicion, codigo_equipo) 
VALUES ('Luis', 'Alberto', 'Santos', 'Ramírez', 'Xela', DATE '1996-09-30', 'Centrocampista', 2);

INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, municipio, fecha_nacimiento, posicion, codigo_equipo) 
VALUES ('Erick', NULL, 'Gómez', 'Paz', 'Cobán', DATE '1994-11-05', 'Delantero', 3);

INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, municipio, fecha_nacimiento, posicion, codigo_equipo) 
VALUES ('Jorge', 'Iván', 'Castillo', 'Morales', 'Cobán', DATE '1997-02-18', 'Defensa', 3);


-- Insertar correos de jugadores
INSERT INTO CorreoJugador (codigo_jugador, correo) VALUES (7, 'jose.perez@realmixco.gt');
INSERT INTO CorreoJugador (codigo_jugador, correo) VALUES (7, 'jperez10@liga.gt');
INSERT INTO CorreoJugador (codigo_jugador, correo) VALUES (8, 'mario.lopez@realmixco.gt');
INSERT INTO CorreoJugador (codigo_jugador, correo) VALUES (9, 'carlos.ruiz@xelaju.gt');
INSERT INTO CorreoJugador (codigo_jugador, correo) VALUES (10, 'luis.santos@xelaju.gt');
INSERT INTO CorreoJugador (codigo_jugador, correo) VALUES (11, 'erick.gomez@coban.gt');
INSERT INTO CorreoJugador (codigo_jugador, correo) VALUES (12, 'jorge.castillo@coban.gt');



-- Insertar partidos
INSERT INTO Partido (fecha, goles_casa, goles_fuera, codigo_equipo_casa, codigo_equipo_fuera) 
VALUES (DATE '2025-10-01', 2, 1, 1, 2);

INSERT INTO Partido (fecha, goles_casa, goles_fuera, codigo_equipo_casa, codigo_equipo_fuera) 
VALUES (DATE '2025-10-08', 3, 2, 3, 1);

-- Insertar goles
INSERT ALL
    INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
    VALUES (3, 6, 15, 'Gol de cabeza tras tiro de esquina')
    INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
    VALUES (3, 7, 45, 'Gol de penal')
    INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
    VALUES (4, 9, 60, 'Gol de tiro libre')
    INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
    VALUES (4, 10, 10, 'Gol de jugada colectiva')
    INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
    VALUES (4, 6, 55, 'Gol de rebote')
    INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
    VALUES (3, 8, 70, 'Gol de contraataque')
    INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
    VALUES (4, 8, 85, 'Gol de volea')
SELECT 1 FROM DUAL;

