CREATE TABLE Departamento (
    codigo_departamento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL
);

CREATE TABLE Municipio (
    codigo_municipio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    codigo_departamento NUMBER NOT NULL,
    CONSTRAINT fk_municipio_departamento FOREIGN KEY (codigo_departamento)
        REFERENCES Departamento(codigo_departamento)
);

CREATE TABLE Presidente (
    dpi VARCHAR2(15) PRIMARY KEY,
    nombre1 VARCHAR2(50) NOT NULL,
    nombre2 VARCHAR2(50),
    nombre3 VARCHAR2(50),
    apellido1 VARCHAR2(50) NOT NULL,
    apellido2 VARCHAR2(50),
    fecha_nacimiento DATE NOT NULL,
    codigo_municipio NUMBER NOT NULL,
    anio_elegido NUMBER(4) NOT NULL,
    codigo_equipo NUMBER UNIQUE,
    CONSTRAINT fk_presidente_equipo FOREIGN KEY (codigo_equipo)
        REFERENCES Equipo(codigo_equipo),
    CONSTRAINT fk_presidente_municipio FOREIGN KEY (codigo_municipio)
        REFERENCES Municipio(codigo_municipio)
);

CREATE TABLE CorreoPresidente (
    id_correo_presidente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dpi VARCHAR2(15) NOT NULL,
    correo VARCHAR2(100) NOT NULL,
    CONSTRAINT fk_correo_presidente FOREIGN KEY (dpi)
        REFERENCES Presidente(dpi)
);

CREATE TABLE Jugador (
    codigo_jugador NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre1 VARCHAR2(50) NOT NULL,
    nombre2 VARCHAR2(50),
    apellido1 VARCHAR2(50) NOT NULL,
    apellido2 VARCHAR2(50),
    fecha_nacimiento DATE NOT NULL,
    posicion VARCHAR2(20) CHECK (posicion IN ('Portero','Defensa','Delantero','Centrocampista')),
    codigo_municipio NUMBER NOT NULL,
    codigo_equipo NUMBER NOT NULL,
    CONSTRAINT fk_jugador_equipo FOREIGN KEY (codigo_equipo)
        REFERENCES Equipo(codigo_equipo),
    CONSTRAINT fk_jugador_municipio FOREIGN KEY (codigo_municipio)
        REFERENCES Municipio(codigo_municipio)
);

CREATE TABLE CorreoJugador (
    id_correo_jugador NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_jugador NUMBER NOT NULL,
    correo VARCHAR2(100) NOT NULL,
    CONSTRAINT fk_correo_jugador FOREIGN KEY (codigo_jugador)
        REFERENCES Jugador(codigo_jugador)
);

CREATE TABLE Partido (
    codigo_partido NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    goles_casa NUMBER DEFAULT 0,
    goles_fuera NUMBER DEFAULT 0,
    codigo_equipo_casa NUMBER NOT NULL,
    codigo_equipo_fuera NUMBER NOT NULL,
    CONSTRAINT fk_partido_equipo_casa FOREIGN KEY (codigo_equipo_casa)
        REFERENCES Equipo(codigo_equipo),
    CONSTRAINT fk_partido_equipo_fuera FOREIGN KEY (codigo_equipo_fuera)
        REFERENCES Equipo(codigo_equipo)
);

CREATE TABLE Gol (
    id_gol NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_partido NUMBER NOT NULL,
    codigo_jugador NUMBER NOT NULL,
    minuto NUMBER NOT NULL,
    descripcion VARCHAR2(255),
    CONSTRAINT fk_gol_partido FOREIGN KEY (codigo_partido)
        REFERENCES Partido(codigo_partido),
    CONSTRAINT fk_gol_jugador FOREIGN KEY (codigo_jugador)
        REFERENCES Jugador(codigo_jugador)
);

-- 1. Insertar Departamentos de Guatemala
INSERT INTO Departamento (nombre) VALUES ('Alta Verapaz');
INSERT INTO Departamento (nombre) VALUES ('Baja Verapaz');
INSERT INTO Departamento (nombre) VALUES ('Chimaltenango');
INSERT INTO Departamento (nombre) VALUES ('Chiquimula');
INSERT INTO Departamento (nombre) VALUES ('El Progreso');
INSERT INTO Departamento (nombre) VALUES ('Escuintla');
INSERT INTO Departamento (nombre) VALUES ('Guatemala');
INSERT INTO Departamento (nombre) VALUES ('Huehuetenango');
INSERT INTO Departamento (nombre) VALUES ('Izabal');
INSERT INTO Departamento (nombre) VALUES ('Jalapa');
INSERT INTO Departamento (nombre) VALUES ('Jutiapa');
INSERT INTO Departamento (nombre) VALUES ('Petén');
INSERT INTO Departamento (nombre) VALUES ('Quetzaltenango');
INSERT INTO Departamento (nombre) VALUES ('Quiché');
INSERT INTO Departamento (nombre) VALUES ('Retalhuleu');
INSERT INTO Departamento (nombre) VALUES ('Sacatepéquez');
INSERT INTO Departamento (nombre) VALUES ('San Marcos');
INSERT INTO Departamento (nombre) VALUES ('Santa Rosa');
INSERT INTO Departamento (nombre) VALUES ('Sololá');
INSERT INTO Departamento (nombre) VALUES ('Suchitepéquez');
INSERT INTO Departamento (nombre) VALUES ('Totonicapán');
INSERT INTO Departamento (nombre) VALUES ('Zacapa');
COMMIT;

-- 2. Insertar Municipios
-- Municipios de Guatemala (Departamento 7)
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Guatemala City', 7);
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Mixco', 7);
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Villa Nueva', 7);
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('San Miguel Petapa', 7);

-- Municipios de Sacatepéquez (Departamento 16)
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Antigua Guatemala', 16);
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Jocotenango', 16);
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Ciudad Vieja', 16);

-- Municipios de Quetzaltenango (Departamento 13)
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Quetzaltenango', 13);
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Salcajá', 13);
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Olintepeque', 13);

-- Municipios de Escuintla (Departamento 6)
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Escuintla', 6);
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Santa Lucía Cotzumalguapa', 6);
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('La Democracia', 6);

-- Municipios de Chimaltenango (Departamento 3)
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Chimaltenango', 3);
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('San Martín Jilotepeque', 3);
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Comalapa', 3);

-- Municipios de Petén (Departamento 12)
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Flores', 12);
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('San Benito', 12);
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('San Andrés', 12);
COMMIT;

-- 3. Insertar Equipos
INSERT INTO Equipo (nombre, estadio, aforo, fundacion, codigo_departamento) 
VALUES ('Club Deportivo Municipal', 'Estadio Municipal', 15000, 1950, 7);
INSERT INTO Equipo (nombre, estadio, aforo, fundacion, codigo_departamento) 
VALUES ('Antigua FC', 'Estadio Pensativo', 12000, 1955, 16);
INSERT INTO Equipo (nombre, estadio, aforo, fundacion, codigo_departamento) 
VALUES ('Quetzaltecos FC', 'Estadio Mario Camposeco', 10000, 1960, 13);
INSERT INTO Equipo (nombre, estadio, aforo, fundacion, codigo_departamento) 
VALUES ('Escuintla FC', 'Estadio Ricardo Muñoz', 8000, 1965, 6);
INSERT INTO Equipo (nombre, estadio, aforo, fundacion, codigo_departamento) 
VALUES ('Chimaltenango SC', 'Estadio Municipal de Chimal', 7000, 1970, 3);
INSERT INTO Equipo (nombre, estadio, aforo, fundacion, codigo_departamento) 
VALUES ('Petén United', 'Estadio Julián Tesucún', 6000, 1975, 12);
COMMIT;

-- 4. Insertar Presidentes
INSERT INTO Presidente (dpi, nombre1, nombre2, nombre3, apellido1, apellido2, fecha_nacimiento, codigo_municipio, anio_elegido, codigo_equipo) 
VALUES ('1234567890101', 'Juan', 'Carlos', NULL, 'García', 'López', TO_DATE('1970-05-15', 'YYYY-MM-DD'), 1, 2020, 1);
INSERT INTO Presidente (dpi, nombre1, nombre2, nombre3, apellido1, apellido2, fecha_nacimiento, codigo_municipio, anio_elegido, codigo_equipo) 
VALUES ('1234567890102', 'María', 'Elena', NULL, 'Rodríguez', 'Martínez', TO_DATE('1975-08-20', 'YYYY-MM-DD'), 5, 2021, 2);
INSERT INTO Presidente (dpi, nombre1, nombre2, nombre3, apellido1, apellido2, fecha_nacimiento, codigo_municipio, anio_elegido, codigo_equipo) 
VALUES ('1234567890103', 'Pedro', 'Antonio', NULL, 'Hernández', 'Gómez', TO_DATE('1968-03-10', 'YYYY-MM-DD'), 8, 2019, 3);
INSERT INTO Presidente (dpi, nombre1, nombre2, nombre3, apellido1, apellido2, fecha_nacimiento, codigo_municipio, anio_elegido, codigo_equipo) 
VALUES ('1234567890104', 'Ana', 'Lucía', NULL, 'Pérez', 'Díaz', TO_DATE('1972-11-25', 'YYYY-MM-DD'), 11, 2020, 4);
INSERT INTO Presidente (dpi, nombre1, nombre2, nombre3, apellido1, apellido2, fecha_nacimiento, codigo_municipio, anio_elegido, codigo_equipo) 
VALUES ('1234567890105', 'Carlos', 'Alberto', NULL, 'López', 'Santos', TO_DATE('1978-07-30', 'YYYY-MM-DD'), 14, 2022, 5);
INSERT INTO Presidente (dpi, nombre1, nombre2, nombre3, apellido1, apellido2, fecha_nacimiento, codigo_municipio, anio_elegido, codigo_equipo) 
VALUES ('1234567890106', 'Sofia', 'Gabriela', NULL, 'Morales', 'Ramírez', TO_DATE('1973-12-05', 'YYYY-MM-DD'), 17, 2021, 6);
COMMIT;

-- 5. Insertar Correos de Presidentes
INSERT INTO CorreoPresidente (dpi, correo) VALUES ('1234567890101', 'juan.garcia@municipal.com');
INSERT INTO CorreoPresidente (dpi, correo) VALUES ('1234567890102', 'maria.rodriguez@antiguafc.com');
INSERT INTO CorreoPresidente (dpi, correo) VALUES ('1234567890103', 'pedro.hernandez@quetzaltecos.com');
INSERT INTO CorreoPresidente (dpi, correo) VALUES ('1234567890104', 'ana.perez@escuintlafc.com');
INSERT INTO CorreoPresidente (dpi, correo) VALUES ('1234567890105', 'carlos.lopez@chimaltenango.com');
INSERT INTO CorreoPresidente (dpi, correo) VALUES ('1234567890106', 'sofia.morales@petenunited.com');
COMMIT;

-- 6. Insertar Jugadores - Equipo 1: Club Deportivo Municipal (12 jugadores)
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Luis', NULL, 'Méndez', 'García', TO_DATE('1995-03-15', 'YYYY-MM-DD'), 'Portero', 1, 1);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Carlos', 'Alberto', 'López', 'Pérez', TO_DATE('1993-06-20', 'YYYY-MM-DD'), 'Defensa', 1, 1);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('José', 'María', 'González', 'Santos', TO_DATE('1994-02-10', 'YYYY-MM-DD'), 'Defensa', 2, 1);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Miguel', 'Ángel', 'Ramírez', 'Díaz', TO_DATE('1992-11-05', 'YYYY-MM-DD'), 'Defensa', 1, 1);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Jorge', 'Luis', 'Hernández', 'Martínez', TO_DATE('1996-08-15', 'YYYY-MM-DD'), 'Defensa', 3, 1);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Roberto', 'Carlos', 'Silva', 'Gómez', TO_DATE('1991-04-25', 'YYYY-MM-DD'), 'Centrocampista', 1, 1);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('David', NULL, 'Morales', 'López', TO_DATE('1993-07-30', 'YYYY-MM-DD'), 'Centrocampista', 2, 1);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Francisco', NULL, 'Castro', 'Rodríguez', TO_DATE('1994-09-12', 'YYYY-MM-DD'), 'Defensa', 1, 1);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Javier', NULL, 'Ortega', 'Hernández', TO_DATE('1995-12-08', 'YYYY-MM-DD'), 'Defensa', 4, 1);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Diego', 'Armando', 'Fernández', 'Gutiérrez', TO_DATE('1990-05-18', 'YYYY-MM-DD'), 'Delantero', 1, 1);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Santiago', NULL, 'Rojas', 'Mendoza', TO_DATE('1992-03-22', 'YYYY-MM-DD'), 'Delantero', 2, 1);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Ángel', 'Gabriel', 'Vargas', 'Castro', TO_DATE('1996-11-14', 'YYYY-MM-DD'), 'Delantero', 1, 1);
COMMIT;

-- Equipo 2: Antigua FC (12 jugadores)
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Oscar', NULL, 'Díaz', 'Luna', TO_DATE('1994-04-10', 'YYYY-MM-DD'), 'Portero', 5, 2);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Ricardo', NULL, 'Morales', 'Sandoval', TO_DATE('1992-07-15', 'YYYY-MM-DD'), 'Defensa', 5, 2);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Fernando', NULL, 'Castillo', 'Reyes', TO_DATE('1993-09-20', 'YYYY-MM-DD'), 'Defensa', 6, 2);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Eduardo', NULL, 'Juárez', 'Méndez', TO_DATE('1995-01-25', 'YYYY-MM-DD'), 'Defensa', 5, 2);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Raúl', NULL, 'Salazar', 'Ortiz', TO_DATE('1991-12-30', 'YYYY-MM-DD'), 'Defensa', 6, 2);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Alberto', NULL, 'Miranda', 'Fuentes', TO_DATE('1990-03-05', 'YYYY-MM-DD'), 'Centrocampista', 5, 2);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Gabriel', NULL, 'Ríos', 'Delgado', TO_DATE('1994-06-18', 'YYYY-MM-DD'), 'Centrocampista', 7, 2);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Mauricio', NULL, 'Paredes', 'Zepeda', TO_DATE('1993-08-22', 'YYYY-MM-DD'), 'Defensa', 5, 2);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Rodrigo', NULL, 'Quintana', 'Vega', TO_DATE('1996-02-14', 'YYYY-MM-DD'), 'Defensa', 6, 2);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Andrés', NULL, 'Salguero', 'Barrios', TO_DATE('1989-11-08', 'YYYY-MM-DD'), 'Delantero', 5, 2);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Fabio', NULL, 'Tobar', 'Arango', TO_DATE('1992-04-12', 'YYYY-MM-DD'), 'Delantero', 7, 2);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Esteban', NULL, 'Urrutia', 'Samayoa', TO_DATE('1995-07-26', 'YYYY-MM-DD'), 'Delantero', 5, 2);
COMMIT;

-- Equipo 3: Quetzaltecos FC (12 jugadores)
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Mario', NULL, 'Alvarez', 'Gomez', TO_DATE('1993-05-12', 'YYYY-MM-DD'), 'Portero', 8, 3);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Julián', NULL, 'Martínez', 'López', TO_DATE('1994-08-22', 'YYYY-MM-DD'), 'Defensa', 8, 3);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Pablo', NULL, 'Santos', 'Ramírez', TO_DATE('1992-11-30', 'YYYY-MM-DD'), 'Defensa', 9, 3);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Daniel', NULL, 'Castro', 'Morales', TO_DATE('1995-02-14', 'YYYY-MM-DD'), 'Defensa', 8, 3);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Samuel', NULL, 'Ordoñez', 'Paz', TO_DATE('1991-07-08', 'YYYY-MM-DD'), 'Defensa', 10, 3);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Leonardo', NULL, 'Fuentes', 'Solís', TO_DATE('1990-09-25', 'YYYY-MM-DD'), 'Centrocampista', 8, 3);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Emilio', NULL, 'Vargas', 'Reyes', TO_DATE('1993-12-18', 'YYYY-MM-DD'), 'Centrocampista', 9, 3);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('René', NULL, 'Mendoza', 'Gutiérrez', TO_DATE('1994-03-07', 'YYYY-MM-DD'), 'Defensa', 8, 3);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Felipe', NULL, 'Salazar', 'Torres', TO_DATE('1996-06-11', 'YYYY-MM-DD'), 'Defensa', 10, 3);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Roberto', NULL, 'Díaz', 'Mendoza', TO_DATE('1988-10-05', 'YYYY-MM-DD'), 'Delantero', 8, 3);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('César', NULL, 'Luna', 'Figueroa', TO_DATE('1992-01-28', 'YYYY-MM-DD'), 'Delantero', 9, 3);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Óscar', NULL, 'Pérez', 'Santos', TO_DATE('1995-04-15', 'YYYY-MM-DD'), 'Delantero', 8, 3);
COMMIT;

-- Equipo 4: Escuintla FC (12 jugadores)
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Héctor', NULL, 'Guzmán', 'Rojas', TO_DATE('1994-06-20', 'YYYY-MM-DD'), 'Portero', 11, 4);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Adrián', NULL, 'Silva', 'Méndez', TO_DATE('1993-09-14', 'YYYY-MM-DD'), 'Defensa', 11, 4);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Gerardo', NULL, 'Romero', 'Castro', TO_DATE('1995-01-08', 'YYYY-MM-DD'), 'Defensa', 12, 4);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Sergio', NULL, 'Navarro', 'Ortega', TO_DATE('1992-04-03', 'YYYY-MM-DD'), 'Defensa', 11, 4);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Arturo', NULL, 'Molina', 'Vega', TO_DATE('1991-07-27', 'YYYY-MM-DD'), 'Defensa', 13, 4);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Federico', NULL, 'Rivas', 'Paredes', TO_DATE('1990-10-12', 'YYYY-MM-DD'), 'Centrocampista', 11, 4);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Guillermo', NULL, 'Cordero', 'Quintana', TO_DATE('1994-02-17', 'YYYY-MM-DD'), 'Centrocampista', 12, 4);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Humberto', NULL, 'Peña', 'Salguero', TO_DATE('1993-05-22', 'YYYY-MM-DD'), 'Defensa', 11, 4);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Rolando', NULL, 'Miranda', 'Tobar', TO_DATE('1996-08-09', 'YYYY-MM-DD'), 'Defensa', 13, 4);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Gustavo', NULL, 'Cifuentes', 'Urrutia', TO_DATE('1989-11-30', 'YYYY-MM-DD'), 'Delantero', 11, 4);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Ricardo', NULL, 'Arriola', 'Alvarez', TO_DATE('1992-03-14', 'YYYY-MM-DD'), 'Delantero', 12, 4);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Nelson', NULL, 'Barrios', 'Martínez', TO_DATE('1995-06-08', 'YYYY-MM-DD'), 'Delantero', 11, 4);
COMMIT;

-- Equipo 5: Chimaltenango SC (12 jugadores)
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Walter', NULL, 'Solís', 'García', TO_DATE('1992-08-25', 'YYYY-MM-DD'), 'Portero', 14, 5);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Edwin', NULL, 'Peralta', 'López', TO_DATE('1994-11-19', 'YYYY-MM-DD'), 'Defensa', 14, 5);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Byron', NULL, 'Castellanos', 'Santos', TO_DATE('1993-02-12', 'YYYY-MM-DD'), 'Defensa', 15, 5);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Marvin', NULL, 'Godínez', 'Ramírez', TO_DATE('1991-05-07', 'YYYY-MM-DD'), 'Defensa', 14, 5);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Erick', NULL, 'Arroyo', 'Díaz', TO_DATE('1996-07-31', 'YYYY-MM-DD'), 'Defensa', 16, 5);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Manuel', NULL, 'Escobar', 'Gómez', TO_DATE('1990-10-24', 'YYYY-MM-DD'), 'Centrocampista', 14, 5);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Joaquín', NULL, 'Villatoro', 'López', TO_DATE('1994-01-18', 'YYYY-MM-DD'), 'Centrocampista', 15, 5);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Rubén', NULL, 'Aguilar', 'Rodríguez', TO_DATE('1993-04-13', 'YYYY-MM-DD'), 'Defensa', 14, 5);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Moisés', NULL, 'Carrillo', 'Hernández', TO_DATE('1995-09-06', 'YYYY-MM-DD'), 'Defensa', 16, 5);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Axel', NULL, 'Valdez', 'Gutiérrez', TO_DATE('1988-12-01', 'YYYY-MM-DD'), 'Delantero', 14, 5);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Kevin', NULL, 'Ramos', 'Mendoza', TO_DATE('1992-02-25', 'YYYY-MM-DD'), 'Delantero', 15, 5);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Brayan', NULL, 'Sosa', 'Castro', TO_DATE('1995-05-20', 'YYYY-MM-DD'), 'Delantero', 14, 5);
COMMIT;

-- Equipo 6: Petén United (12 jugadores)
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Jorge', NULL, 'Tzul', 'Pérez', TO_DATE('1993-07-10', 'YYYY-MM-DD'), 'Portero', 17, 6);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Luis', 'Fernando', 'Choc', 'García', TO_DATE('1994-10-04', 'YYYY-MM-DD'), 'Defensa', 17, 6);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Carlos', 'Enrique', 'Cac', 'López', TO_DATE('1992-12-29', 'YYYY-MM-DD'), 'Defensa', 18, 6);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Juan', 'Pablo', 'Tun', 'Martínez', TO_DATE('1991-03-23', 'YYYY-MM-DD'), 'Defensa', 17, 6);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Diego', 'Alejandro', 'Puzul', 'Rodríguez', TO_DATE('1996-06-16', 'YYYY-MM-DD'), 'Defensa', 19, 6);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('José', 'Miguel', 'Ical', 'Gómez', TO_DATE('1990-09-09', 'YYYY-MM-DD'), 'Centrocampista', 17, 6);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Miguel', 'Ángel', 'Pop', 'López', TO_DATE('1994-12-03', 'YYYY-MM-DD'), 'Centrocampista', 18, 6);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Francisco', 'Javier', 'Tzib', 'Hernández', TO_DATE('1993-02-26', 'YYYY-MM-DD'), 'Defensa', 17, 6);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Javier', 'Antonio', 'Cux', 'Gutiérrez', TO_DATE('1995-05-21', 'YYYY-MM-DD'), 'Defensa', 19, 6);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Sergio', 'Daniel', 'Ché', 'Mendoza', TO_DATE('1989-08-14', 'YYYY-MM-DD'), 'Delantero', 17, 6);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('David', 'Esteban', 'Pascual', 'Castro', TO_DATE('1992-11-07', 'YYYY-MM-DD'), 'Delantero', 18, 6);
INSERT INTO Jugador (nombre1, nombre2, apellido1, apellido2, fecha_nacimiento, posicion, codigo_municipio, codigo_equipo) 
VALUES ('Óscar', 'René', 'Tzec', 'Vargas', TO_DATE('1995-01-31', 'YYYY-MM-DD'), 'Delantero', 17, 6);
COMMIT;

-- 7. Insertar Correos de Jugadores (2 por jugador como ejemplo para los primeros 6 jugadores)
INSERT INTO CorreoJugador (codigo_jugador, correo) VALUES (1, 'luis.mendez@municipal.com');
INSERT INTO CorreoJugador (codigo_jugador, correo) VALUES (1, 'lmendez@gmail.com');
INSERT INTO CorreoJugador (codigo_jugador, correo) VALUES (2, 'carlos.lopez@municipal.com');
INSERT INTO CorreoJugador (codigo_jugador, correo) VALUES (3, 'jose.gonzalez@municipal.com');
INSERT INTO CorreoJugador (codigo_jugador, correo) VALUES (4, 'miguel.ramirez@municipal.com');
INSERT INTO CorreoJugador (codigo_jugador, correo) VALUES (5, 'jorge.hernandez@municipal.com');
INSERT INTO CorreoJugador (codigo_jugador, correo) VALUES (6, 'roberto.silva@municipal.com');
INSERT INTO CorreoJugador (codigo_jugador, correo) VALUES (7, 'david.morales@municipal.com');
INSERT INTO CorreoJugador (codigo_jugador, correo) VALUES (8, 'francisco.castro@municipal.com');
INSERT INTO CorreoJugador (codigo_jugador, correo) VALUES (9, 'javier.ortega@municipal.com');
INSERT INTO CorreoJugador (codigo_jugador, correo) VALUES (10, 'diego.fernandez@municipal.com');
INSERT INTO CorreoJugador (codigo_jugador, correo) VALUES (11, 'santiago.rojas@municipal.com');
INSERT INTO CorreoJugador (codigo_jugador, correo) VALUES (12, 'angel.vargas@municipal.com');
COMMIT;

-- 8. Insertar Partidos
INSERT INTO Partido (fecha, goles_casa, goles_fuera, codigo_equipo_casa, codigo_equipo_fuera) 
VALUES (TO_DATE('2024-01-10', 'YYYY-MM-DD'), 2, 1, 1, 2);
INSERT INTO Partido (fecha, goles_casa, goles_fuera, codigo_equipo_casa, codigo_equipo_fuera) 
VALUES (TO_DATE('2024-01-15', 'YYYY-MM-DD'), 3, 3, 3, 4);
INSERT INTO Partido (fecha, goles_casa, goles_fuera, codigo_equipo_casa, codigo_equipo_fuera) 
VALUES (TO_DATE('2024-01-20', 'YYYY-MM-DD'), 1, 0, 5, 6);
INSERT INTO Partido (fecha, goles_casa, goles_fuera, codigo_equipo_casa, codigo_equipo_fuera) 
VALUES (TO_DATE('2024-01-25', 'YYYY-MM-DD'), 2, 2, 2, 3);
INSERT INTO Partido (fecha, goles_casa, goles_fuera, codigo_equipo_casa, codigo_equipo_fuera) 
VALUES (TO_DATE('2024-02-01', 'YYYY-MM-DD'), 4, 1, 4, 5);
INSERT INTO Partido (fecha, goles_casa, goles_fuera, codigo_equipo_casa, codigo_equipo_fuera) 
VALUES (TO_DATE('2024-02-08', 'YYYY-MM-DD'), 0, 2, 6, 1);
INSERT INTO Partido (fecha, goles_casa, goles_fuera, codigo_equipo_casa, codigo_equipo_fuera) 
VALUES (TO_DATE('2024-02-15', 'YYYY-MM-DD'), 1, 1, 2, 4);
INSERT INTO Partido (fecha, goles_casa, goles_fuera, codigo_equipo_casa, codigo_equipo_fuera) 
VALUES (TO_DATE('2024-02-22', 'YYYY-MM-DD'), 3, 0, 3, 6);
COMMIT;

-- 9. Insertar 20 Goles distribuidos
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (1, 10, 15, 'Gol de cabeza en área chica');
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (1, 11, 38, 'Tiro libre directo');
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (1, 23, 65, 'Gol en contraataque');
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (2, 25, 12, 'Gol de penal');
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (2, 26, 28, 'Gol de tiro lejano');
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (2, 34, 45, 'Gol de esquina directa');
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (2, 35, 52, 'Gol en jugada colectiva');
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (2, 36, 67, 'Gol de chilena');
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (2, 28, 89, 'Gol en último minuto');
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (3, 45, 23, 'Gol de falta');
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (4, 23, 18, 'Gol de tiro libre');
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (4, 24, 34, 'Gol en mano a mano');
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (4, 25, 55, 'Gol de cabeza');
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (4, 26, 71, 'Gol de media distancia');
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (5, 34, 8, 'Gol rápido');
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (5, 35, 22, 'Gol de penal');
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (5, 36, 45, 'Gol de tacón');
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (5, 37, 68, 'Gol en rebote');
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (5, 45, 75, 'Gol de consuelo');
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (6, 10, 40, 'Gol de volea');
INSERT INTO Gol (codigo_partido, codigo_jugador, minuto, descripcion) 
VALUES (6, 11, 83, 'Gol definición');
COMMIT;



-- Procedimiento para insertar un nuevo equipo
CREATE OR REPLACE PROCEDURE InsertarEquipo(
    p_nombre IN VARCHAR2,
    p_estadio IN VARCHAR2,
    p_aforo IN NUMBER,
    p_fundacion IN NUMBER,
    p_codigo_departamento IN NUMBER
) AS
BEGIN
    INSERT INTO Equipo (nombre, estadio, aforo, fundacion, codigo_departamento)
    VALUES (p_nombre, p_estadio, p_aforo, p_fundacion, p_codigo_departamento);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Equipo insertado correctamente');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error al insertar equipo: ' || SQLERRM);
END;
/

-- Procedimiento para transferir un jugador entre equipos
CREATE OR REPLACE PROCEDURE TransferirJugador(
    p_codigo_jugador IN NUMBER,
    p_codigo_equipo_destino IN NUMBER
) AS
    v_equipo_actual NUMBER;
BEGIN
    -- Verificar si el jugador existe
    SELECT codigo_equipo INTO v_equipo_actual
    FROM Jugador
    WHERE codigo_jugador = p_codigo_jugador;
    
    IF v_equipo_actual = p_codigo_equipo_destino THEN
        DBMS_OUTPUT.PUT_LINE('El jugador ya pertenece a este equipo');
        RETURN;
    END IF;
    
    -- Actualizar el equipo del jugador
    UPDATE Jugador
    SET codigo_equipo = p_codigo_equipo_destino
    WHERE codigo_jugador = p_codigo_jugador;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Jugador transferido correctamente del equipo ' || 
                        v_equipo_actual || ' al equipo ' || p_codigo_equipo_destino);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Jugador no encontrado');
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error en transferencia: ' || SQLERRM);
END;
/

-- Procedimiento para registrar un partido completo
CREATE OR REPLACE PROCEDURE RegistrarPartido(
    p_fecha IN DATE,
    p_equipo_casa IN NUMBER,
    p_equipo_fuera IN NUMBER
) AS
    v_partido_id NUMBER;
BEGIN
    -- Insertar el partido
    INSERT INTO Partido (fecha, codigo_equipo_casa, codigo_equipo_fuera)
    VALUES (p_fecha, p_equipo_casa, p_equipo_fuera)
    RETURNING codigo_partido INTO v_partido_id;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Partido registrado con ID: ' || v_partido_id);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error al registrar partido: ' || SQLERRM);
END;
/

-- Procedimiento para obtener estadísticas de un equipo
CREATE OR REPLACE PROCEDURE EstadisticasEquipo(
    p_codigo_equipo IN NUMBER
) AS
    v_total_jugadores NUMBER;
    v_promedio_edad NUMBER;
    v_porteros NUMBER;
    v_defensas NUMBER;
    v_centrocampistas NUMBER;
    v_delanteros NUMBER;
BEGIN
    -- Total de jugadores
    SELECT COUNT(*) INTO v_total_jugadores
    FROM Jugador
    WHERE codigo_equipo = p_codigo_equipo;
    
    -- Promedio de edad
    SELECT AVG(EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM fecha_nacimiento))
    INTO v_promedio_edad
    FROM Jugador
    WHERE codigo_equipo = p_codigo_equipo;
    
    -- Jugadores por posición
    SELECT COUNT(*) INTO v_porteros
    FROM Jugador
    WHERE codigo_equipo = p_codigo_equipo AND posicion = 'Portero';
    
    SELECT COUNT(*) INTO v_defensas
    FROM Jugador
    WHERE codigo_equipo = p_codigo_equipo AND posicion = 'Defensa';
    
    SELECT COUNT(*) INTO v_centrocampistas
    FROM Jugador
    WHERE codigo_equipo = p_codigo_equipo AND posicion = 'Centrocampista';
    
    SELECT COUNT(*) INTO v_delanteros
    FROM Jugador
    WHERE codigo_equipo = p_codigo_equipo AND posicion = 'Delantero';
    
    -- Mostrar resultados
    DBMS_OUTPUT.PUT_LINE('=== ESTADÍSTICAS DEL EQUIPO ===');
    DBMS_OUTPUT.PUT_LINE('Total jugadores: ' || v_total_jugadores);
    DBMS_OUTPUT.PUT_LINE('Promedio edad: ' || ROUND(v_promedio_edad, 1));
    DBMS_OUTPUT.PUT_LINE('Porteros: ' || v_porteros);
    DBMS_OUTPUT.PUT_LINE('Defensas: ' || v_defensas);
    DBMS_OUTPUT.PUT_LINE('Centrocampistas: ' || v_centrocampistas);
    DBMS_OUTPUT.PUT_LINE('Delanteros: ' || v_delanteros);
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Equipo no encontrado');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al obtener estadísticas: ' || SQLERRM);
END;
/

-- Procedimiento para limpiar datos antiguos
CREATE OR REPLACE PROCEDURE LimpiarDatosAntiguos(
    p_fecha_limite IN DATE
) AS
    v_partidos_eliminados NUMBER := 0;
    v_goles_eliminados NUMBER := 0;
BEGIN
    -- Eliminar goles de partidos antiguos
    DELETE FROM Gol
    WHERE codigo_partido IN (
        SELECT codigo_partido
        FROM Partido
        WHERE fecha < p_fecha_limite
    );
    v_goles_eliminados := SQL%ROWCOUNT;
    
    -- Eliminar partidos antiguos
    DELETE FROM Partido
    WHERE fecha < p_fecha_limite;
    v_partidos_eliminados := SQL%ROWCOUNT;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Limpieza completada:');
    DBMS_OUTPUT.PUT_LINE('- Partidos eliminados: ' || v_partidos_eliminados);
    DBMS_OUTPUT.PUT_LINE('- Goles eliminados: ' || v_goles_eliminados);
    
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error en limpieza: ' || SQLERRM);
END;
/


-- Trigger para validar la edad del jugador (mínimo 16 años)
CREATE OR REPLACE TRIGGER TR_ValidarEdadJugador
BEFORE INSERT OR UPDATE ON Jugador
FOR EACH ROW
DECLARE
    v_edad NUMBER;
BEGIN
    v_edad := EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM :NEW.fecha_nacimiento);
    
    IF v_edad < 16 THEN
        RAISE_APPLICATION_ERROR(-20001, 'El jugador debe tener al menos 16 años');
    END IF;
END;
/

-- Trigger para validar que un equipo no juegue contra sí mismo
CREATE OR REPLACE TRIGGER TR_ValidarEquiposPartido
BEFORE INSERT OR UPDATE ON Partido
FOR EACH ROW
BEGIN
    IF :NEW.codigo_equipo_casa = :NEW.codigo_equipo_fuera THEN
        RAISE_APPLICATION_ERROR(-20002, 'Un equipo no puede jugar contra sí mismo');
    END IF;
END;
/

-- Trigger para auditar cambios en la tabla Equipo
CREATE TABLE AuditoriaEquipo (
    id_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_equipo NUMBER,
    accion VARCHAR2(10),
    usuario VARCHAR2(50),
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    datos_anteriores VARCHAR2(1000)
);

CREATE OR REPLACE TRIGGER TR_AuditoriaEquipo
AFTER INSERT OR UPDATE OR DELETE ON Equipo
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO AuditoriaEquipo (codigo_equipo, accion, usuario, datos_anteriores)
        VALUES (:NEW.codigo_equipo, 'INSERT', USER, 
               'Nuevo equipo: ' || :NEW.nombre);
    ELSIF UPDATING THEN
        INSERT INTO AuditoriaEquipo (codigo_equipo, accion, usuario, datos_anteriores)
        VALUES (:OLD.codigo_equipo, 'UPDATE', USER,
               'Cambios: ' || :OLD.nombre || ' -> ' || :NEW.nombre);
    ELSIF DELETING THEN
        INSERT INTO AuditoriaEquipo (codigo_equipo, accion, usuario, datos_anteriores)
        VALUES (:OLD.codigo_equipo, 'DELETE', USER,
               'Eliminado: ' || :OLD.nombre);
    END IF;
END;
/

-- Trigger para mantener consistencia en goles
CREATE OR REPLACE TRIGGER TR_ActualizarGolesPartido
AFTER INSERT OR UPDATE OR DELETE ON Gol
DECLARE
    CURSOR c_partidos IS
        SELECT DISTINCT codigo_partido FROM Gol;
BEGIN
    FOR rec IN c_partidos LOOP
        UPDATE Partido p
        SET goles_casa = (
            SELECT COUNT(*)
            FROM Gol g
            JOIN Jugador j ON g.codigo_jugador = j.codigo_jugador
            WHERE g.codigo_partido = p.codigo_partido
            AND j.codigo_equipo = p.codigo_equipo_casa
        ),
        goles_fuera = (
            SELECT COUNT(*)
            FROM Gol g
            JOIN Jugador j ON g.codigo_jugador = j.codigo_jugador
            WHERE g.codigo_partido = p.codigo_partido
            AND j.codigo_equipo = p.codigo_equipo_fuera
        )
        WHERE p.codigo_partido = rec.codigo_partido;
    END LOOP;
END;
/

-- Trigger para validar que un presidente tenga al menos 30 años
CREATE OR REPLACE TRIGGER TR_ValidarEdadPresidente
BEFORE INSERT OR UPDATE ON Presidente
FOR EACH ROW
DECLARE
    v_edad NUMBER;
BEGIN
    v_edad := EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM :NEW.fecha_nacimiento);
    
    IF v_edad < 30 THEN
        RAISE_APPLICATION_ERROR(-20003, 'El presidente debe tener al menos 30 años');
    END IF;
END;
/

-- Trigger para evitar duplicados de correos
CREATE OR REPLACE TRIGGER TR_ValidarCorreoUnico
BEFORE INSERT ON CorreoJugador
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM CorreoJugador
    WHERE correo = :NEW.correo;
    
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20004, 'El correo electrónico ya está registrado');
    END IF;
END;
/

-- Función para calcular la edad de una persona
CREATE OR REPLACE FUNCTION CalcularEdad(
    p_fecha_nacimiento IN DATE
) RETURN NUMBER AS
    v_edad NUMBER;
BEGIN
    v_edad := EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM p_fecha_nacimiento);
    RETURN v_edad;
END;
/

-- Función para obtener el goleador de un equipo
CREATE OR REPLACE FUNCTION ObtenerGoleadorEquipo(
    p_codigo_equipo IN NUMBER
) RETURN VARCHAR2 AS
    v_goleador VARCHAR2(100);
    v_goles NUMBER;
BEGIN
    SELECT j.nombre1 || ' ' || j.apellido1, COUNT(*)
    INTO v_goleador, v_goles
    FROM Jugador j
    JOIN Gol g ON j.codigo_jugador = g.codigo_jugador
    WHERE j.codigo_equipo = p_codigo_equipo
    GROUP BY j.nombre1, j.apellido1
    ORDER BY COUNT(*) DESC
    FETCH FIRST 1 ROW ONLY;
    
    RETURN v_goleador || ' (' || v_goles || ' goles)';
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Sin goles registrados';
    WHEN OTHERS THEN
        RETURN 'Error al calcular';
END;
/

-- Función para verificar aforo del estadio
CREATE OR REPLACE FUNCTION VerificarAforo(
    p_codigo_equipo IN NUMBER,
    p_espectadores IN NUMBER
) RETURN VARCHAR2 AS
    v_aforo_maximo NUMBER;
BEGIN
    SELECT aforo INTO v_aforo_maximo
    FROM Equipo
    WHERE codigo_equipo = p_codigo_equipo;
    
    IF p_espectadores > v_aforo_maximo THEN
        RETURN 'EXCEDIDO - Aforo máximo: ' || v_aforo_maximo;
    ELSE
        RETURN 'DENTRO DEL LÍMITE - Capacidad: ' || 
               ROUND((p_espectadores / v_aforo_maximo) * 100, 1) || '%';
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Equipo no encontrado';
END;
/
