ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = LIGAPRO;

-- ============================================================================
-- Creación de tablas
-- ============================================================================

CREATE TABLE Departamento (
    codigo_departamento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE Municipio (
    codigo_municipio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    codigo_departamento NUMBER NOT NULL,
    CONSTRAINT fk_municipio_departamento FOREIGN KEY (codigo_departamento)
        REFERENCES Departamento (codigo_departamento),
    CONSTRAINT uq_municipio UNIQUE (nombre, codigo_departamento)
);

CREATE TABLE Equipo (
    codigo_equipo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    estadio VARCHAR2(100) NOT NULL,
    aforo NUMBER NOT NULL,
    fundacion NUMBER(4) NOT NULL,
    codigo_departamento NUMBER NOT NULL,
    CONSTRAINT fk_equipo_departamento FOREIGN KEY (codigo_departamento)
        REFERENCES Departamento (codigo_departamento)
);

CREATE TABLE Presidente (
    dpi VARCHAR2(15) PRIMARY KEY,
    nombre1 VARCHAR2(50) NOT NULL,
    nombre2 VARCHAR2(50),
    nombre3 VARCHAR2(50),
    apellido1 VARCHAR2(50) NOT NULL,
    apellido2 VARCHAR2(50),
    fecha_nacimiento DATE NOT NULL,
    correo_electronico VARCHAR2(100),
    codigo_municipio NUMBER NOT NULL,
    anio_elegido NUMBER(4) NOT NULL,
    codigo_equipo NUMBER UNIQUE,
    CONSTRAINT fk_presidente_municipio FOREIGN KEY (codigo_municipio)
        REFERENCES Municipio (codigo_municipio),
    CONSTRAINT fk_presidente_equipo FOREIGN KEY (codigo_equipo)
        REFERENCES Equipo (codigo_equipo)
);

CREATE TABLE CorreoPresidente (
    id_correo_presidente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo_electronico VARCHAR2(100) NOT NULL,
    dpi VARCHAR2(15) NOT NULL,
    CONSTRAINT fk_correo_presidente FOREIGN KEY (dpi)
        REFERENCES Presidente (dpi)
);

CREATE TABLE Jugador (
    codigo_jugador NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre1 VARCHAR2(50) NOT NULL,
    nombre2 VARCHAR2(50),
    apellido1 VARCHAR2(50) NOT NULL,
    apellido2 VARCHAR2(50),
    correo_electronico VARCHAR2(100),
    codigo_municipio NUMBER NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    posicion VARCHAR2(20) CHECK (posicion IN ('Portero','Defensa','Delantero','Centrocampista')),
    codigo_equipo NUMBER NOT NULL,
    CONSTRAINT fk_jugador_municipio FOREIGN KEY (codigo_municipio)
        REFERENCES Municipio (codigo_municipio),
    CONSTRAINT fk_jugador_equipo FOREIGN KEY (codigo_equipo)
        REFERENCES Equipo (codigo_equipo)
);

CREATE TABLE CorreoJugador (
    id_correo_jugador NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo VARCHAR2(100) NOT NULL,
    codigo_jugador NUMBER NOT NULL,
    CONSTRAINT fk_correo_jugador FOREIGN KEY (codigo_jugador)
        REFERENCES Jugador (codigo_jugador)
);

CREATE TABLE Partido (
    codigo_partido NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    goles_casa NUMBER DEFAULT 0,
    goles_fuera NUMBER DEFAULT 0,
    codigo_equipo_casa NUMBER NOT NULL,
    codigo_equipo_fuera NUMBER NOT NULL,
    CONSTRAINT fk_partido_equipo_casa FOREIGN KEY (codigo_equipo_casa)
        REFERENCES Equipo (codigo_equipo),
    CONSTRAINT fk_partido_equipo_fuera FOREIGN KEY (codigo_equipo_fuera)
        REFERENCES Equipo (codigo_equipo)
);

CREATE TABLE Gol (
    id_gol NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    minuto NUMBER NOT NULL,
    descripcion VARCHAR2(255),
    codigo_jugador NUMBER NOT NULL,
    codigo_partido NUMBER NOT NULL,
    CONSTRAINT fk_gol_jugador FOREIGN KEY (codigo_jugador)
        REFERENCES Jugador (codigo_jugador),
    CONSTRAINT fk_gol_partido FOREIGN KEY (codigo_partido)
        REFERENCES Partido (codigo_partido)
);

CREATE TABLE AuditoriaEquipo (
    id_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_equipo NUMBER,
    accion VARCHAR2(10),
    usuario VARCHAR2(50),
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    datos_anteriores VARCHAR2(1000)
);

-- ============================================================================
-- Datos de prueba
-- ============================================================================

INSERT INTO Departamento (nombre) VALUES ('Guatemala');
INSERT INTO Departamento (nombre) VALUES ('Quetzaltenango');
INSERT INTO Departamento (nombre) VALUES ('Alta Verapaz');
INSERT INTO Departamento (nombre) VALUES ('Sacatepéquez');

INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Guatemala', 1);
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Mixco', 1);
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Villa Nueva', 1);
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Quetzaltenango', 2);
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Olintepeque', 2);
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Cobán', 3);
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('San Pedro Carchá', 3);
INSERT INTO Municipio (nombre, codigo_departamento) VALUES ('Antigua Guatemala', 4);

INSERT INTO Equipo (nombre, estadio, aforo, fundacion, codigo_departamento)
VALUES ('Real Mixco', 'Estadio Santo Domingo', 15000, 1970, 1);
INSERT INTO Equipo (nombre, estadio, aforo, fundacion, codigo_departamento)
VALUES ('Xelajú MC', 'Estadio Mario Camposeco', 11000, 1942, 2);
INSERT INTO Equipo (nombre, estadio, aforo, fundacion, codigo_departamento)
VALUES ('Cobán Imperial', 'Estadio Verapaz', 12000, 1936, 3);

INSERT INTO Presidente (
    dpi, nombre1, nombre2, nombre3, apellido1, apellido2,
    fecha_nacimiento, correo_electronico, codigo_municipio, anio_elegido, codigo_equipo
) VALUES (
    '1234567890101', 'Carlos', 'Enrique', NULL, 'Ramírez', 'López',
    DATE '1975-06-15', 'carlos.ramirez@realmixco.gt', 2, 2020, 1
);

INSERT INTO Presidente (
    dpi, nombre1, nombre2, nombre3, apellido1, apellido2,
    fecha_nacimiento, correo_electronico, codigo_municipio, anio_elegido, codigo_equipo
) VALUES (
    '9876543210101', 'Luis', 'Fernando', NULL, 'Gómez', 'Martínez',
    DATE '1980-03-22', 'luis.gomez@coban.gt', 6, 2021, 3
);

INSERT INTO CorreoPresidente (correo_electronico, dpi)
VALUES ('presidente.mixco@liga.gt', '1234567890101');
INSERT INTO CorreoPresidente (correo_electronico, dpi)
VALUES ('contacto.mixco@liga.gt', '1234567890101');
INSERT INTO CorreoPresidente (correo_electronico, dpi)
VALUES ('presidente.coban@liga.gt', '9876543210101');

INSERT INTO Jugador (
    nombre1, nombre2, apellido1, apellido2, correo_electronico,
    codigo_municipio, fecha_nacimiento, posicion, codigo_equipo
) VALUES (
    'José', 'Manuel', 'Pérez', 'García', 'jose.perez@realmixco.gt',
    2, DATE '1995-04-10', 'Delantero', 1
);

INSERT INTO Jugador (
    nombre1, nombre2, apellido1, apellido2, correo_electronico,
    codigo_municipio, fecha_nacimiento, posicion, codigo_equipo
) VALUES (
    'Mario', NULL, 'López', 'Hernández', 'mario.lopez@realmixco.gt',
    1, DATE '1998-07-22', 'Defensa', 1
);

INSERT INTO Jugador (
    nombre1, nombre2, apellido1, apellido2, correo_electronico,
    codigo_municipio, fecha_nacimiento, posicion, codigo_equipo
) VALUES (
    'Carlos', 'Andrés', 'Ruiz', 'Mendoza', 'carlos.ruiz@xelaju.gt',
    4, DATE '1992-01-15', 'Portero', 2
);

INSERT INTO Jugador (
    nombre1, nombre2, apellido1, apellido2, correo_electronico,
    codigo_municipio, fecha_nacimiento, posicion, codigo_equipo
) VALUES (
    'Luis', 'Alberto', 'Santos', 'Ramírez', 'luis.santos@xelaju.gt',
    4, DATE '1996-09-30', 'Centrocampista', 2
);

INSERT INTO Jugador (
    nombre1, nombre2, apellido1, apellido2, correo_electronico,
    codigo_municipio, fecha_nacimiento, posicion, codigo_equipo
) VALUES (
    'Erick', NULL, 'Gómez', 'Paz', 'erick.gomez@coban.gt',
    6, DATE '1994-11-05', 'Delantero', 3
);

INSERT INTO Jugador (
    nombre1, nombre2, apellido1, apellido2, correo_electronico,
    codigo_municipio, fecha_nacimiento, posicion, codigo_equipo
) VALUES (
    'Jorge', 'Iván', 'Castillo', 'Morales', 'jorge.castillo@coban.gt',
    7, DATE '1997-02-18', 'Defensa', 3
);

INSERT INTO CorreoJugador (correo, codigo_jugador) VALUES ('jperez10@liga.gt', 1);
INSERT INTO CorreoJugador (correo, codigo_jugador) VALUES ('mlopez5@liga.gt', 2);
INSERT INTO CorreoJugador (correo, codigo_jugador) VALUES ('cruiz1@liga.gt', 3);
INSERT INTO CorreoJugador (correo, codigo_jugador) VALUES ('lsantos8@liga.gt', 4);
INSERT INTO CorreoJugador (correo, codigo_jugador) VALUES ('egomez9@liga.gt', 5);
INSERT INTO CorreoJugador (correo, codigo_jugador) VALUES ('jcastillo4@liga.gt', 6);

INSERT INTO Partido (fecha, goles_casa, goles_fuera, codigo_equipo_casa, codigo_equipo_fuera)
VALUES (DATE '2025-10-01', 2, 1, 1, 2);

INSERT INTO Partido (fecha, goles_casa, goles_fuera, codigo_equipo_casa, codigo_equipo_fuera)
VALUES (DATE '2025-10-08', 3, 2, 3, 1);

INSERT INTO Gol (minuto, descripcion, codigo_jugador, codigo_partido)
VALUES (15, 'Gol de cabeza tras tiro de esquina', 5, 1);

INSERT INTO Gol (minuto, descripcion, codigo_jugador, codigo_partido)
VALUES (45, 'Gol de penal', 1, 1);

INSERT INTO Gol (minuto, descripcion, codigo_jugador, codigo_partido)
VALUES (60, 'Gol de tiro libre', 3, 2);

INSERT INTO Gol (minuto, descripcion, codigo_jugador, codigo_partido)
VALUES (10, 'Gol de jugada colectiva', 4, 2);

INSERT INTO Gol (minuto, descripcion, codigo_jugador, codigo_partido)
VALUES (55, 'Gol de rebote', 5, 2);

INSERT INTO Gol (minuto, descripcion, codigo_jugador, codigo_partido)
VALUES (70, 'Gol de contraataque', 2, 1);

INSERT INTO Gol (minuto, descripcion, codigo_jugador, codigo_partido)
VALUES (85, 'Gol de volea', 2, 2);

COMMIT;

-- ============================================================================
-- Procedimientos almacenados
-- ============================================================================

CREATE OR REPLACE PROCEDURE InsertarEquipo(
    p_nombre IN VARCHAR2,
    p_estadio IN VARCHAR2,
    p_aforo IN NUMBER,
    p_fundacion IN NUMBER,
    p_codigo_departamento IN NUMBER
) AS
BEGIN
    INSERT INTO Equipo (nombre, estadio, aforo, fundacion, codigo_departamento)
    VALUES (p_nombre, p_estadio, p_aforo, p_fundacion, p_codigo_departamento);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Equipo insertado correctamente');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error al insertar equipo: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE TransferirJugador(
    p_codigo_jugador IN NUMBER,
    p_codigo_equipo_destino IN NUMBER
) AS
    v_equipo_actual NUMBER;
BEGIN
    SELECT codigo_equipo
    INTO v_equipo_actual
    FROM Jugador
    WHERE codigo_jugador = p_codigo_jugador;

    IF v_equipo_actual = p_codigo_equipo_destino THEN
        DBMS_OUTPUT.PUT_LINE('El jugador ya pertenece a este equipo');
        RETURN;
    END IF;

    UPDATE Jugador
    SET codigo_equipo = p_codigo_equipo_destino
    WHERE codigo_jugador = p_codigo_jugador;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE(
        'Jugador transferido correctamente del equipo ' || v_equipo_actual ||
        ' al equipo ' || p_codigo_equipo_destino
    );
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Jugador no encontrado');
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error en transferencia: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE RegistrarPartido(
    p_fecha IN DATE,
    p_equipo_casa IN NUMBER,
    p_equipo_fuera IN NUMBER
) AS
    v_partido_id NUMBER;
BEGIN
    INSERT INTO Partido (fecha, codigo_equipo_casa, codigo_equipo_fuera)
    VALUES (p_fecha, p_equipo_casa, p_equipo_fuera)
    RETURNING codigo_partido INTO v_partido_id;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Partido registrado con ID: ' || v_partido_id);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error al registrar partido: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE EstadisticasEquipo(
    p_codigo_equipo IN NUMBER
) AS
    v_total_jugadores NUMBER;
    v_promedio_edad NUMBER;
    v_porteros NUMBER;
    v_defensas NUMBER;
    v_centrocampistas NUMBER;
    v_delanteros NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_total_jugadores
    FROM Jugador
    WHERE codigo_equipo = p_codigo_equipo;

    SELECT AVG(TRUNC(MONTHS_BETWEEN(SYSDATE, fecha_nacimiento) / 12))
    INTO v_promedio_edad
    FROM Jugador
    WHERE codigo_equipo = p_codigo_equipo;

    SELECT COUNT(*) INTO v_porteros
    FROM Jugador
    WHERE codigo_equipo = p_codigo_equipo AND posicion = 'Portero';

    SELECT COUNT(*) INTO v_defensas
    FROM Jugador
    WHERE codigo_equipo = p_codigo_equipo AND posicion = 'Defensa';

    SELECT COUNT(*) INTO v_centrocampistas
    FROM Jugador
    WHERE codigo_equipo = p_codigo_equipo AND posicion = 'Centrocampista';

    SELECT COUNT(*) INTO v_delanteros
    FROM Jugador
    WHERE codigo_equipo = p_codigo_equipo AND posicion = 'Delantero';

    DBMS_OUTPUT.PUT_LINE('=== ESTADÍSTICAS DEL EQUIPO ===');
    DBMS_OUTPUT.PUT_LINE('Total jugadores: ' || v_total_jugadores);
    DBMS_OUTPUT.PUT_LINE('Promedio edad: ' || NVL(ROUND(v_promedio_edad, 1), 0));
    DBMS_OUTPUT.PUT_LINE('Porteros: ' || v_porteros);
    DBMS_OUTPUT.PUT_LINE('Defensas: ' || v_defensas);
    DBMS_OUTPUT.PUT_LINE('Centrocampistas: ' || v_centrocampistas);
    DBMS_OUTPUT.PUT_LINE('Delanteros: ' || v_delanteros);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Equipo no encontrado');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al obtener estadísticas: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE LimpiarDatosAntiguos(
    p_fecha_limite IN DATE
) AS
    v_partidos_eliminados NUMBER := 0;
    v_goles_eliminados NUMBER := 0;
BEGIN
    DELETE FROM Gol
    WHERE codigo_partido IN (
        SELECT codigo_partido
        FROM Partido
        WHERE fecha < p_fecha_limite
    );
    v_goles_eliminados := SQL%ROWCOUNT;

    DELETE FROM Partido
    WHERE fecha < p_fecha_limite;
    v_partidos_eliminados := SQL%ROWCOUNT;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Limpieza completada:');
    DBMS_OUTPUT.PUT_LINE('- Partidos eliminados: ' || v_partidos_eliminados);
    DBMS_OUTPUT.PUT_LINE('- Goles eliminados: ' || v_goles_eliminados);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error en limpieza: ' || SQLERRM);
END;
/

-- ============================================================================
-- Triggers
-- ============================================================================

CREATE OR REPLACE TRIGGER TR_ValidarEdadJugador
BEFORE INSERT OR UPDATE ON Jugador
FOR EACH ROW
DECLARE
    v_edad NUMBER;
BEGIN
    v_edad := TRUNC(MONTHS_BETWEEN(SYSDATE, :NEW.fecha_nacimiento) / 12);
    IF v_edad < 16 THEN
        RAISE_APPLICATION_ERROR(-20001, 'El jugador debe tener al menos 16 años');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TR_ValidarEquiposPartido
BEFORE INSERT OR UPDATE ON Partido
FOR EACH ROW
BEGIN
    IF :NEW.codigo_equipo_casa = :NEW.codigo_equipo_fuera THEN
        RAISE_APPLICATION_ERROR(-20002, 'Un equipo no puede jugar contra sí mismo');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TR_AuditoriaEquipo
AFTER INSERT OR UPDATE OR DELETE ON Equipo
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO AuditoriaEquipo (codigo_equipo, accion, usuario, datos_anteriores)
        VALUES (:NEW.codigo_equipo, 'INSERT', USER, 'Nuevo equipo: ' || :NEW.nombre);
    ELSIF UPDATING THEN
        INSERT INTO AuditoriaEquipo (codigo_equipo, accion, usuario, datos_anteriores)
        VALUES (:OLD.codigo_equipo, 'UPDATE', USER,
                'Nombre anterior: ' || :OLD.nombre || ', actual: ' || :NEW.nombre);
    ELSIF DELETING THEN
        INSERT INTO AuditoriaEquipo (codigo_equipo, accion, usuario, datos_anteriores)
        VALUES (:OLD.codigo_equipo, 'DELETE', USER, 'Eliminado: ' || :OLD.nombre);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TR_ActualizarGolesPartido
AFTER INSERT OR UPDATE OR DELETE ON Gol
BEGIN
    UPDATE Partido p
    SET goles_casa = (
            SELECT COUNT(*)
            FROM Gol g
            JOIN Jugador j ON g.codigo_jugador = j.codigo_jugador
            WHERE g.codigo_partido = p.codigo_partido
              AND j.codigo_equipo = p.codigo_equipo_casa
        ),
        goles_fuera = (
            SELECT COUNT(*)
            FROM Gol g
            JOIN Jugador j ON g.codigo_jugador = j.codigo_jugador
            WHERE g.codigo_partido = p.codigo_partido
              AND j.codigo_equipo = p.codigo_equipo_fuera
        );
END;
/

CREATE OR REPLACE TRIGGER TR_ValidarEdadPresidente
BEFORE INSERT OR UPDATE ON Presidente
FOR EACH ROW
DECLARE
    v_edad NUMBER;
BEGIN
    v_edad := TRUNC(MONTHS_BETWEEN(SYSDATE, :NEW.fecha_nacimiento) / 12);
    IF v_edad < 30 THEN
        RAISE_APPLICATION_ERROR(-20003, 'El presidente debe tener al menos 30 años');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TR_ValidarCorreoUnico
BEFORE INSERT ON CorreoJugador
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM CorreoJugador
    WHERE UPPER(correo) = UPPER(:NEW.correo);

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20004, 'El correo electrónico ya está registrado');
    END IF;
END;
/

-- ============================================================================
-- Funciones
-- ============================================================================

CREATE OR REPLACE FUNCTION CalcularEdad(
    p_fecha_nacimiento IN DATE
) RETURN NUMBER AS
BEGIN
    RETURN TRUNC(MONTHS_BETWEEN(SYSDATE, p_fecha_nacimiento) / 12);
END;
/

CREATE OR REPLACE FUNCTION ObtenerGoleadorEquipo(
    p_codigo_equipo IN NUMBER
) RETURN VARCHAR2 AS
    v_goleador VARCHAR2(100);
    v_goles NUMBER;
BEGIN
    SELECT j.nombre1 || ' ' || j.apellido1, COUNT(*)
    INTO v_goleador, v_goles
    FROM Jugador j
    JOIN Gol g ON j.codigo_jugador = g.codigo_jugador
    WHERE j.codigo_equipo = p_codigo_equipo
    GROUP BY j.nombre1, j.apellido1
    ORDER BY COUNT(*) DESC
    FETCH FIRST 1 ROW ONLY;

    RETURN v_goleador || ' (' || v_goles || ' goles)';
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Sin goles registrados';
    WHEN OTHERS THEN
        RETURN 'Error al calcular';
END;
/

CREATE OR REPLACE FUNCTION VerificarAforo(
    p_codigo_equipo IN NUMBER,
    p_espectadores IN NUMBER
) RETURN VARCHAR2 AS
    v_aforo_maximo NUMBER;
BEGIN
    SELECT aforo
    INTO v_aforo_maximo
    FROM Equipo
    WHERE codigo_equipo = p_codigo_equipo;

    IF p_espectadores > v_aforo_maximo THEN
        RETURN 'EXCEDIDO - Aforo máximo: ' || v_aforo_maximo;
    ELSE
        RETURN 'DENTRO DEL LÍMITE - Capacidad: ' ||
            ROUND((p_espectadores / v_aforo_maximo) * 100, 1) || '%';
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Equipo no encontrado';
END;
/

COMMIT;


